package com.techelevator.campgrounds.model;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.jar.Attributes.Name;


public interface ReservationDAO {

	public Reservation getReservationById(Long id);
	public Reservation getReservationByName(String name);
	public BigDecimal calculateReservationCost(long reservationId);
	public Reservation makeReservation(Long siteId, String name, String startDate, String endDate);//returns the reservation Id primary key generated by the database as the confirmation number
	public Reservation createNewReservation(Reservation newReservation);
}

